/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.User;
import fn.Boton;
import fn.FnInfo;
import fn.FnUser;
import fn.GlobalValues;
import fn.Icons;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo G470
 */
public class Acceso extends javax.swing.JFrame {

    FnInfo load = new FnInfo();
    Boton boton = new Boton();
    /**
     * Creates new form Acceso
     */
    
    public Acceso() {
        initComponents();
        GlobalValues.VERSION = "4.0.0";
        try{
           load.loadXml(); 
        }catch(Exception e){
            System.out.println("Acceso: Error al cargar xml");
        }
        if(!load.isActive())
            JOptionPane.showMessageDialog(null,"La licencia ha caducado","Es necesaria la renovación de la Licencia",JOptionPane.ERROR_MESSAGE);
        txtUser.setText(load.getStaticUser());
        load.probarConexion();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
//        this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 450, 300);
        this.setLocationRelativeTo(null);
        //Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/logo.png"));
        //setIconImage(icon);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png"));
        setIconImage(icon);
        this.setTitle("OptiData "+GlobalValues.VERSION);
        this.titulo.setText("OptiData "+GlobalValues.VERSION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnter = new javax.swing.JLabel();
        btnSyncronize17 = new javax.swing.JLabel();
        btnSyncronize16 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        logoSDXERP = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Enter_32px.png"))); // NOI18N
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnterMouseExited(evt);
            }
        });
        getContentPane().add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        btnSyncronize17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_User_Male_32px.png"))); // NOI18N
        btnSyncronize17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSyncronize17MouseClicked(evt);
            }
        });
        getContentPane().add(btnSyncronize17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        btnSyncronize16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Password_32px.png"))); // NOI18N
        btnSyncronize16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSyncronize16MouseClicked(evt);
            }
        });
        getContentPane().add(btnSyncronize16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        titulo.setFont(new java.awt.Font("Aharoni", 0, 10)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Dcs Optics v 4.1.6");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        txtPass.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 51, 51));
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 142, -1));

        txtUser.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(51, 51, 51));
        txtUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 142, -1));

        logoSDXERP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"))); // NOI18N
        getContentPane().add(logoSDXERP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 190, 220));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 401, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnSyncronize16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncronize16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSyncronize16MouseClicked

    private void btnSyncronize17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncronize17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSyncronize17MouseClicked

    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseClicked
        entrar();
    }//GEN-LAST:event_btnEnterMouseClicked

    private void btnEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseEntered
        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnEnter.getIcon().toString()))));
    }//GEN-LAST:event_btnEnterMouseEntered

    private void btnEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseExited
        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnEnter.getIcon().toString()))));
    }//GEN-LAST:event_btnEnterMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    private void entrar(){
        String user = txtUser.getText();
        String pass = txtPass.getText();
        FnUser upUser = new FnUser();
        User usu;
        try{
            usu=upUser.validar(user,pass);
            if(usu!=null){
                        this.setVisible(false);
                        try{
                            GlobalValues.USERNAME = usu.getNombre();
                            GlobalValues.ID_USER = usu.getId();
                            ContentAdmin principalAdmin = new ContentAdmin();
                            principalAdmin.setVisible(true);
//                            load.setStaticUser(user);
                            this.dispose();
                        }catch(ClassNotFoundException | SQLException ex){
                            JOptionPane.showMessageDialog(null, "Error. No se pueden cargar los datos."+ex.getMessage(),"Datos de acceso",JOptionPane.WARNING_MESSAGE);
                        }

            }else{
                JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos","Datos de acceso",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error. No se pueden cargar los datos.\nEs probable que el servidor no se haya iniciado.","Datos de acceso",JOptionPane.WARNING_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEnter;
    private javax.swing.JLabel btnSyncronize16;
    private javax.swing.JLabel btnSyncronize17;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel logoSDXERP;
    private javax.swing.JLabel titulo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
