/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import fn.Boton;
import fn.GV;
import fn.Icons;
import fn.OptionPane;
import fn.SubProcess;
import fn.globalValues.GlobalValuesBD;
import fn.globalValues.GlobalValuesFunctions;
import fn.globalValues.GlobalValuesVariables;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RootPaneContainer;
import view.opanel.OpanelConfig;
import view.opanel.OpanelInventario;
import view.opanel.OpanelTools;
import view.opanel.OpanelUserData;

/**
 *
 * @author Lenovo G470
 */
public class ContentAdmin extends javax.swing.JFrame {

    Boton boton = new Boton();
//    public static String TITLE = "";
    
    
    
    /**
     * Creates new form ContentAdmin
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public ContentAdmin() throws SQLException, ClassNotFoundException{
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//        this.lblUserName.setText(GV.USER.getNombre());
        this.lblName.setText(GV.projectName()+" "+GV.version());
        this.lblTitle.setText(GV.projectName());
        
        centrarPantalla();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png"));
        setIconImage(icon);
        
        setLblLicencia();
        lblSync();
        String userName = (GV.user()!=null) ? GV.user().getNombre():"";
        lblUserName.setText(userName);
        if(GV.licenciaTipoPlan()==GlobalValuesVariables.licenciaTipoFree()){
            btnSyncronize.setVisible(false);
        }
        setLblLicencia();
        
        try {
            boton.crearFicha();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Es probable que el servidor no se haya iniciado, Inicie el servicio y vuelva a abrir el programa.","Error de conexion",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);//opcion cerrar
        }
    }
    
    public void setWaitCursor() {
        JFrame frame = ContentAdmin.this;
        if (frame != null) {
            RootPaneContainer root = (RootPaneContainer) frame.getRootPane().getTopLevelAncestor();
            root.getGlassPane().setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            root.getGlassPane().setVisible(true);
        }
    }

    public void setDefaultCursor() {
        JFrame frame = ContentAdmin.this;
        if (frame != null) {
            RootPaneContainer root = (RootPaneContainer) frame.getRootPane().getTopLevelAncestor();
            root.getGlassPane().setCursor(Cursor.getDefaultCursor());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        principalAdmin = new javax.swing.JPanel();
        jpUpBar = new javax.swing.JPanel();
        btnSizeWindow = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        btnUser = new javax.swing.JLabel();
        btnMessage = new javax.swing.JLabel();
        btnConfig = new javax.swing.JLabel();
        btnInvent = new javax.swing.JLabel();
        btnSyncronize = new javax.swing.JLabel();
        btnTools = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnMinimizeWindow = new javax.swing.JLabel();
        lblLicence = new javax.swing.JLabel();
        jpSuperior = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jpLeftBar = new javax.swing.JPanel();
        btnCrearFicha = new javax.swing.JLabel();
        btnDoctores = new javax.swing.JLabel();
        btnListarFichas = new javax.swing.JLabel();
        btnClientes = new javax.swing.JLabel();
        btnInstituciones = new javax.swing.JLabel();
        btnConvenios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        principalAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout principalAdminLayout = new javax.swing.GroupLayout(principalAdmin);
        principalAdmin.setLayout(principalAdminLayout);
        principalAdminLayout.setHorizontalGroup(
            principalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        principalAdminLayout.setVerticalGroup(
            principalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpUpBar.setBackground(new java.awt.Color(255, 255, 255));
        jpUpBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Maximize_Window_25px.png"))); // NOI18N
        btnSizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSizeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSizeWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSizeWindowMouseExited(evt);
            }
        });
        jpUpBar.add(btnSizeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, -1, -1));

        lblUserName.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblUserName.setText("Username");
        jpUpBar.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 240, 20));

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_25px.png"))); // NOI18N
        btnUser.setToolTipText("Mis datos");
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        jpUpBar.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        btnMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Msg_1_25px.png"))); // NOI18N
        btnMessage.setToolTipText("Mensajes");
        btnMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMessageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMessageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMessageMouseExited(evt);
            }
        });
        jpUpBar.add(btnMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Settings_25px.png"))); // NOI18N
        btnConfig.setToolTipText("Configuracion");
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfigMouseExited(evt);
            }
        });
        jpUpBar.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        btnInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Choice_25px.png"))); // NOI18N
        btnInvent.setToolTipText("Inventario");
        btnInvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventMouseExited(evt);
            }
        });
        jpUpBar.add(btnInvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        btnSyncronize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Uninstalling_Updates_25px.png"))); // NOI18N
        btnSyncronize.setToolTipText("Sincronizar datos");
        btnSyncronize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSyncronizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSyncronizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSyncronizeMouseExited(evt);
            }
        });
        jpUpBar.add(btnSyncronize, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Maintenance_25px.png"))); // NOI18N
        btnTools.setToolTipText("Herramientas");
        btnTools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnToolsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnToolsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnToolsMouseExited(evt);
            }
        });
        jpUpBar.add(btnTools, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Close_Window_25px.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        jpUpBar.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        btnMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Minimize_Window_25px.png"))); // NOI18N
        btnMinimizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeWindowMouseExited(evt);
            }
        });
        jpUpBar.add(btnMinimizeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        lblLicence.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblLicence.setText("Estado de licencia");
        jpUpBar.add(lblLicence, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 340, 20));

        jpSuperior.setBackground(new java.awt.Color(242, 240, 237));
        jpSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblName.setText("OptiData vX.X.X");
        jpSuperior.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblTitle.setText("Nueva Ficha");
        jpSuperior.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jpLeftBar.setBackground(new java.awt.Color(108, 217, 186));

        btnCrearFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_New_Resume_Template_50px.png"))); // NOI18N
        btnCrearFicha.setToolTipText("Nueva Ficha");
        btnCrearFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearFichaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearFichaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearFichaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearFichaMousePressed(evt);
            }
        });

        btnDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Lab_Coat_50px.png"))); // NOI18N
        btnDoctores.setToolTipText("Profesionales");
        btnDoctores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoctoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoctoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoctoresMouseExited(evt);
            }
        });

        btnListarFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_List_50px.png"))); // NOI18N
        btnListarFichas.setToolTipText("Fichas");
        btnListarFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarFichasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarFichasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarFichasMouseExited(evt);
            }
        });

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Reception_50px.png"))); // NOI18N
        btnClientes.setToolTipText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });

        btnInstituciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Organization_50px.png"))); // NOI18N
        btnInstituciones.setToolTipText("Instituciones");
        btnInstituciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInstitucionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInstitucionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInstitucionesMouseExited(evt);
            }
        });

        btnConvenios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Handshake_50px.png"))); // NOI18N
        btnConvenios.setToolTipText("Convenios");
        btnConvenios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConveniosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConveniosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConveniosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpLeftBarLayout = new javax.swing.GroupLayout(jpLeftBar);
        jpLeftBar.setLayout(jpLeftBarLayout);
        jpLeftBarLayout.setHorizontalGroup(
            jpLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftBarLayout.createSequentialGroup()
                .addGroup(jpLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearFicha)
                    .addComponent(btnListarFichas)
                    .addComponent(btnClientes)
                    .addComponent(btnDoctores)
                    .addComponent(btnInstituciones)
                    .addComponent(btnConvenios))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jpLeftBarLayout.setVerticalGroup(
            jpLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftBarLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnCrearFicha)
                .addGap(5, 5, 5)
                .addComponent(btnListarFichas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoctores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInstituciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConvenios)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpLeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpUpBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(principalAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpUpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principalAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpLeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            cerrar();
        } catch (SQLException | ClassNotFoundException | InterruptedException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnSizeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSizeWindowMouseClicked
//        if(this.getState() == JFrame.NORMAL)
//            this.setState(JFrame.MAXIMIZED_BOTH);
//        else
//            this.setState(JFrame.NORMAL);
//            this.setState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnSizeWindowMouseClicked

    private void btnMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseClicked
        if(GV.licenciaExpirada()){
            GV.mensajeLicenceExpired();
        }else{
            if(GlobalValuesFunctions.licenciaIsEnableToSendInternMessages()){
               boton.mensajes(); 
            }else{
                GV.mensajeLicenceAccessDenied();
            }
        }
    }//GEN-LAST:event_btnMessageMouseClicked

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        if(GV.tipoUserAdmin()){
            OptionPane.showOptionPanel(new OpanelConfig(), "Configuración");
        }else{
            GV.mensajeAccessDenied();
        }
    }//GEN-LAST:event_btnConfigMouseClicked

    private void btnInventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventMouseClicked
        OptionPane.showOptionPanel(new OpanelInventario(), "Inventario");
    }//GEN-LAST:event_btnInventMouseClicked

    private void btnToolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToolsMouseClicked
        if(GV.tipoUserAdmin()){
            OptionPane.showOptionPanel(new OpanelTools(), OptionPane.titleTool());
        }else{
            GV.mensajeAccessDenied();
        }
    }//GEN-LAST:event_btnToolsMouseClicked

    private void btnToolsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToolsMouseEntered
        
        btnTools.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIconIfActive(btnTools.getIcon().toString()))));
    }//GEN-LAST:event_btnToolsMouseEntered

    private void btnToolsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToolsMouseExited
        btnTools.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnTools.getIcon().toString()))));
    }//GEN-LAST:event_btnToolsMouseExited

    private void btnConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseEntered
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIconIfActive(btnConfig.getIcon().toString()))));
    }//GEN-LAST:event_btnConfigMouseEntered

    private void btnConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseExited
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnConfig.getIcon().toString()))));
    }//GEN-LAST:event_btnConfigMouseExited

    private void btnInventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventMouseEntered
        btnInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnInvent.getIcon().toString()))));
    }//GEN-LAST:event_btnInventMouseEntered

    private void btnInventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventMouseExited
        btnInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnInvent.getIcon().toString()))));
    }//GEN-LAST:event_btnInventMouseExited

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnUser.getIcon().toString()))));
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnUser.getIcon().toString()))));
    }//GEN-LAST:event_btnUserMouseExited

    private void btnMessageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseEntered
        btnMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnMessage.getIcon().toString()))));
    }//GEN-LAST:event_btnMessageMouseEntered

    private void btnMessageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseExited
        btnMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnMessage.getIcon().toString()))));
    }//GEN-LAST:event_btnMessageMouseExited

    private void btnSizeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSizeWindowMouseEntered
        String img = btnSizeWindow.getIcon().toString();
        int index = img.indexOf("/icons");
        img = img.substring(index);
        img = img.replaceAll(".png", "_4.png");
        btnSizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(img)));
    }//GEN-LAST:event_btnSizeWindowMouseEntered

    private void btnSizeWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSizeWindowMouseExited
        String img = btnSizeWindow.getIcon().toString();
        int index = img.indexOf("/icons");
        img = img.substring(index);
        img = img.replaceAll("_4.png", ".png");
        btnSizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(img)));
    }//GEN-LAST:event_btnSizeWindowMouseExited

    private void btnCrearFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFichaMouseClicked
        try {
            boton.crearFicha();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearFichaMouseClicked

    private void btnCrearFichaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFichaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearFichaMousePressed

    private void btnDoctoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctoresMouseClicked
        try {
            boton.doctores();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDoctoresMouseClicked

    private void btnListarFichasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFichasMouseClicked
        try {
            boton.fichas(GV.cboFichasFilter());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarFichasMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        try {
            boton.clientes();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnInstitucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstitucionesMouseClicked
        try {
            boton.instituciones();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInstitucionesMouseClicked

    private void btnCrearFichaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFichaMouseEntered
        
        btnCrearFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnCrearFicha.getIcon().toString()))));
    }//GEN-LAST:event_btnCrearFichaMouseEntered

    private void btnCrearFichaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFichaMouseExited
        
        btnCrearFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnCrearFicha.getIcon().toString()))));
    }//GEN-LAST:event_btnCrearFichaMouseExited

    private void btnListarFichasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFichasMouseEntered
        btnListarFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnListarFichas.getIcon().toString()))));
    }//GEN-LAST:event_btnListarFichasMouseEntered

    private void btnListarFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFichasMouseExited
        btnListarFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnListarFichas.getIcon().toString()))));
    }//GEN-LAST:event_btnListarFichasMouseExited

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnClientes.getIcon().toString()))));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnClientes.getIcon().toString()))));
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnDoctoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctoresMouseEntered
        btnDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnDoctores.getIcon().toString()))));
    }//GEN-LAST:event_btnDoctoresMouseEntered

    private void btnDoctoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctoresMouseExited
        btnDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnDoctores.getIcon().toString()))));
    }//GEN-LAST:event_btnDoctoresMouseExited

    private void btnInstitucionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstitucionesMouseEntered
        
        btnInstituciones.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnInstituciones.getIcon().toString()))));
    }//GEN-LAST:event_btnInstitucionesMouseEntered

    private void btnInstitucionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstitucionesMouseExited
        btnInstituciones.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnInstituciones.getIcon().toString()))));
    }//GEN-LAST:event_btnInstitucionesMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        SubProcess.stopAll();
        
        try {
            cerrar();
        } catch (Exception ex) {
            System.out.println("ERROR en btnCloseMouseClicked.cerrar(): "+ex.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnClose.getIcon().toString()))));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnClose.getIcon().toString()))));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMinimizeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeWindowMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeWindowMouseClicked

    private void btnMinimizeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeWindowMouseEntered
        btnMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnMinimizeWindow.getIcon().toString()))));
    }//GEN-LAST:event_btnMinimizeWindowMouseEntered

    private void btnMinimizeWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeWindowMouseExited
        btnMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnMinimizeWindow.getIcon().toString()))));
    }//GEN-LAST:event_btnMinimizeWindowMouseExited

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        OptionPane.showOptionPanel(new OpanelUserData(), "Mis Datos");
    }//GEN-LAST:event_btnUserMouseClicked

    private void btnConveniosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConveniosMouseClicked
        try {
            boton.convenios();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConveniosMouseClicked

    private void btnConveniosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConveniosMouseEntered
        btnConvenios.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnConvenios.getIcon().toString()))));
    }//GEN-LAST:event_btnConveniosMouseEntered

    private void btnConveniosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConveniosMouseExited
        btnConvenios.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnConvenios.getIcon().toString()))));
    }//GEN-LAST:event_btnConveniosMouseExited

    private void btnSyncronizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncronizeMouseExited
       btnSyncronize.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnSyncronize.getIcon().toString()))));
    }//GEN-LAST:event_btnSyncronizeMouseExited

    private void btnSyncronizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncronizeMouseEntered
        if(GV.isOnline()){
            btnSyncronize.setToolTipText("Sincronizar datos");
        }else{
            btnSyncronize.setToolTipText("Red no disponible");
        }
        btnSyncronize.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIconIfConnected(btnSyncronize.getIcon().toString()))));
    }//GEN-LAST:event_btnSyncronizeMouseEntered

    private void btnSyncronizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncronizeMouseClicked
        if(GV.licenciaExpirada()){
            GV.mensajeLicenceExpired();
        }else{
            if(GV.sincronizacionIsStopped()){
                GV.cursorWAIT();
                SubProcess.SyncAll();
                GV.cursorDF();
            }else{
                OptionPane.showMsg("Imposible efectuar operación", "Ya se encuentra una sincronización en curso", 2);
            }
        }  
    }//GEN-LAST:event_btnSyncronizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ContentAdmin().setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnConfig;
    private javax.swing.JLabel btnConvenios;
    private javax.swing.JLabel btnCrearFicha;
    private javax.swing.JLabel btnDoctores;
    private javax.swing.JLabel btnInstituciones;
    private javax.swing.JLabel btnInvent;
    private javax.swing.JLabel btnListarFichas;
    private javax.swing.JLabel btnMessage;
    private javax.swing.JLabel btnMinimizeWindow;
    private javax.swing.JLabel btnSizeWindow;
    private javax.swing.JLabel btnSyncronize;
    private javax.swing.JLabel btnTools;
    private javax.swing.JLabel btnUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpLeftBar;
    private javax.swing.JPanel jpSuperior;
    private javax.swing.JPanel jpUpBar;
    private javax.swing.JLabel lblLicence;
    private javax.swing.JLabel lblName;
    public static javax.swing.JLabel lblTitle;
    public static javax.swing.JLabel lblUserName;
    public static javax.swing.JPanel principalAdmin;
    // End of variables declaration//GEN-END:variables

    private void centrarPantalla() {
        this.setLocationRelativeTo(null);
    }

    private void cerrar() throws SQLException, ClassNotFoundException, InterruptedException{//cerrar con opciones en nueva implementacion
        if(OptionPane.getConfirmation("Cerrar", "¿Desea cerrar la aplicación?", JOptionPane.INFORMATION_MESSAGE)){
            this.setVisible(false);
            if(OptionPane.getConfirmation("Respaldar información", "¿Deseas respaldar los datos?", JOptionPane.INFORMATION_MESSAGE))
                GlobalValuesBD.backUpLocalBd();
              
            System.exit(0);
        }
    }

    /**
     * imprrme en la información de la licencia el estado de sincronizacion una vez
     * que se encuentra en ejecucion.
     */
    private void lblSync() {
        SubProcess.lblSyncStatus(lblLicence);
    }

    private void setLblLicencia() {
        lblLicence.setText(GV.licenciaEstadoStr());
        this.setTitle(GV.projectName()+" "+GV.version()+"     "+GV.licenciaEstadoStr());
        ExecutorService executor = Executors.newSingleThreadExecutor();
        executor.submit(() -> {
                while(true){
                    String licencia = "";
                    licencia = GV.licenciaEstadoStr();
                    lblLicence.setText(licencia);
                    this.setTitle(GV.projectName()+" "+GV.version()+"     "+licencia);
                }
        });
    }
}
