/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mxrck.autocompleter.TextAutoCompleter;
import dao.Dao;
import entities.Convenio;
import entities.Institucion;
import fn.Boton;
import fn.GV;
import javax.swing.table.DefaultTableModel;
import fn.Icons;
import fn.OptionPane;
import static fn.date.Cmp.localIsNewOrEqual;
import fn.globalValues.GlobalValuesBD;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import view.opanel.OpanelPagarCuotasConvenio;

/**
 *
 * @author home
 */
public class VConvenios extends javax.swing.JPanel {
    Boton boton = new Boton();
    Dao load= new Dao();
    private static Convenio stConvenio =  null;
    private static List<Object> listConvenios = new ArrayList<>();
    TableRowSorter trs;
    DefaultTableModel modelo = new DefaultTableModel() {
           @Override
           public boolean isCellEditable(int fila, int columna) {
               return false; //Con esto conseguimos que la tabla no se pueda editar
           }
        };
    /**
     * Creates new form VClientes
     */
    public VConvenios() throws SQLException, ClassNotFoundException {
        ContentAdmin.lblTitle.setText("Convenios");
        initComponents();
        autocompletar();
        modelo.addColumn("Id");
        modelo.addColumn("Convenio");
        modelo.addColumn("Institución");
        modelo.addColumn("Estado");
        tblListar.setModel(modelo);
        load();
        loadPanels(1);
        GV.cursorDF();
        cDF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboMostrar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListar = new javax.swing.JTable();
        btnAbrir = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnCrearFichas = new javax.swing.JLabel();
        pnl1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        txtFechaIniN = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        txtFechaTerN = new com.toedter.calendar.JDateChooser();
        txtCuotasN = new javax.swing.JSpinner();
        txtInstitucionN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPorcentajeAdicionalN = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        txtFechaCobroN = new com.toedter.calendar.JDateChooser();
        pnl2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreU = new javax.swing.JTextField();
        btnModificar = new javax.swing.JLabel();
        txtFechaIniU = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        txtFechaFinU = new com.toedter.calendar.JDateChooser();
        txtCuotasU = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        txtInstitucionU = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPorcentajeAdicionalU = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        txtFechaCobroU = new com.toedter.calendar.JDateChooser();
        btnPagarCuotas = new javax.swing.JLabel();
        btnMostrarCuotas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 11))); // NOI18N

        cboMostrar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cboMostrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activos", "Eliminados" }));
        cboMostrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMostrarItemStateChanged(evt);
            }
        });

        tblListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Convenio", "Institución", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblListar);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Eye_50px.png"))); // NOI18N
        btnAbrir.setToolTipText("Cargar");
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbrirMouseExited(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Trash_50px.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Data_Backup_50px.png"))); // NOI18N
        btnRestaurar.setToolTipText("Restaurar");
        btnRestaurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestaurarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestaurarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestaurarMouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Search_Property_25px_1.png"))); // NOI18N

        txtBuscar.setToolTipText("Buscar");
        txtBuscar.setBorder(null);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnCrearFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_New_Resume_Template_50px.png"))); // NOI18N
        btnCrearFichas.setToolTipText("Crear fichas con convenio seleccionado");
        btnCrearFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearFichasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearFichasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearFichasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAbrir)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearFichas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRestaurar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboMostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearFichas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36))
        );

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Crear nuevo convenio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel1.setText("Fecha inicio");

        txtNombreN.setToolTipText("Nombre del convenio");
        txtNombreN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreNKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel5.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel7.setText("Cuotas");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel9.setText("Institucion");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Save_50px.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        txtFechaIniN.setToolTipText("Fecha en que se habilitará la aplicacion del convenio");

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel20.setText("Fecha termino");

        txtFechaTerN.setToolTipText("Fecha de vencimiento del convenio, después de esta fecha no se podrán ingresar mas registros con este convenio");

        txtCuotasN.setModel(new javax.swing.SpinnerNumberModel(1, 1, 72, 1));
        txtCuotasN.setToolTipText("Cantidad tope de cuotas mensuales");

        txtInstitucionN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInstitucionNFocusLost(evt);
            }
        });
        txtInstitucionN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstitucionNKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstitucionNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInstitucionNKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel13.setText("% Valor Adicional");

        txtPorcentajeAdicionalN.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        txtPorcentajeAdicionalN.setToolTipText("Aumentar el valor total de los productos para este convenio");

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel21.setText("Fecha de pago");

        txtFechaCobroN.setToolTipText("Fecha de vencimiento del convenio, después de esta fecha no se podrán ingresar mas registros con este convenio");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInstitucionN, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcentajeAdicionalN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addComponent(txtFechaIniN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaTerN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 133, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addComponent(txtCuotasN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaCobroN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl1Layout.createSequentialGroup()
                                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaIniN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtFechaTerN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCuotasN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel21)))
                            .addComponent(txtFechaCobroN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPorcentajeAdicionalN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtInstitucionN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl2.setBackground(new java.awt.Color(108, 217, 186));
        pnl2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Editar convenio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 11))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel10.setText("Nombre");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel11.setText("Fecha inicio");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel12.setText("Cuotas");

        txtNombreU.setToolTipText("Nombre del convenio");
        txtNombreU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUKeyTyped(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Save_50px.png"))); // NOI18N
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });

        txtFechaIniU.setToolTipText("Fecha en que se habilitará la aplicacion del convenio");

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel22.setText("Fecha termino");

        txtFechaFinU.setToolTipText("Fecha de vencimiento del convenio, después de esta fecha no se podrán ingresar mas registros con este convenio");

        txtCuotasU.setModel(new javax.swing.SpinnerNumberModel(1, 1, 72, 1));
        txtCuotasU.setToolTipText("Cantidad tope de cuotas mensuales");

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel24.setText("Institucion");

        txtInstitucionU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInstitucionUFocusLost(evt);
            }
        });
        txtInstitucionU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstitucionUKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstitucionUKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInstitucionUKeyTyped(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Cancel_50px.png"))); // NOI18N
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel15.setText("% Valor Adicional");

        txtPorcentajeAdicionalU.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        txtPorcentajeAdicionalU.setToolTipText("Aumentar el valor total de los productos para este convenio");

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel23.setText("Fecha pago");

        txtFechaCobroU.setToolTipText("Fecha de vencimiento del convenio, después de esta fecha no se podrán ingresar mas registros con este convenio");

        btnPagarCuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Paper_Money_50px.png"))); // NOI18N
        btnPagarCuotas.setToolTipText("Pagar cuotas");
        btnPagarCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarCuotasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagarCuotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagarCuotasMouseExited(evt);
            }
        });

        btnMostrarCuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Stack_of_Money_50px.png"))); // NOI18N
        btnMostrarCuotas.setToolTipText("Mostrar cuotas");
        btnMostrarCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarCuotasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarCuotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarCuotasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaIniU, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuotasU, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaFinU, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaCobroU, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInstitucionU, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcentajeAdicionalU, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarCuotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPagarCuotas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addContainerGap())
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(txtFechaIniU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCuotasU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtFechaFinU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFechaCobroU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtPorcentajeAdicionalU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtInstitucionU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModificar))))
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPagarCuotas)
                    .addComponent(btnMostrarCuotas)
                    .addComponent(btnCancelar)))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel2.setText("Nombre (Es el nombre del convenio que se está registrando)");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel3.setText("Fecha de inicio y término (Es el periodo activado para asignar el convenio a las recetas oftalmológicas)");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel4.setText("Fecha de pago (Primera fecha de cobro, se sumará un mes a partir de la fecha y cantidad de cuotas)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseClicked
        try{
            cWT();
            int fila = tblListar.getSelectedRow();
            int id = Integer.parseInt(tblListar.getValueAt(fila, 0).toString());
            
            abrirConvenio(id);
            
        }catch(Exception e){
            OptionPane.showMsg("Seleccione un elemento en la tabla","Debe hacer clic sobre un elemento de la tabla,\n"
                    + "Luego presione el botón \"Ver\".",  2);
        }
        cDF();
    }//GEN-LAST:event_btnAbrirMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if(GV.tipoUserAdmin()){
            try{
                cWT();
                int fila = tblListar.getSelectedRow();
                int id = Integer.parseInt(tblListar.getValueAt(fila, 0).toString());
                Convenio temp = (Convenio)load.get(null, id, new Convenio());
                if(temp.getEstado() == 2){
                    OptionPane.showMsg("No se puede anular", "Este convenio ya fué generado, por lo tanto es imposible eliminar", 2);
                    cDF();
                    return;
                }
                if(OptionPane.getConfirmation("Eliminar registro", "¿Esta seguro que desea eliminar el convenio "+temp.getNombre()+"?", 2)){
                    cWT();
                    if(!load.restoreOrDeleteFromUI(temp)){
                        cDF();
                        return;
                    }
                }
                cargarDatos("0");

            }catch(Exception e){
                cDF();
                OptionPane.showMsg("Seleccione Convenio","Error al cargar valores,\n"
                        + "es posible que no se haya seleccionado un registro:\n"
                        + "Debe hacer clic sobre un elemento de la tabla,\n"
                        + "Luego presione el botón \"Ver\".\n"
                        + "Otro posible error: el valor seleccionado no tiene un identificador válido.",2);
            }
            cDF();
        }else{
            GV.mensajeAccessDenied();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnRestaurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarMouseClicked
        if(GV.tipoUserAdmin()){
            try{
                cWT();
                int fila = tblListar.getSelectedRow();
                int id = Integer.parseInt(tblListar.getValueAt(fila, 0).toString());
                Convenio temp = (Convenio)load.get(null, id, new Convenio());
                if(OptionPane.getConfirmation("Confirmación de registro", "¿Esta seguro que desea restaurar este registro?", 1)){
                    cWT();
                    if(!load.restoreOrDeleteFromUI(temp)){
                        cDF();
                        return;
                    }
                    cargarDatos("-1");
                }
            }catch(Exception e){
                OptionPane.showMsg("Seleccione Convenio","Error al cargar valores,\n"
                        + "es posible que no se haya seleccionado un registro:\n"
                        + "Debe hacer clic sobre un elemento de la tabla,\n"
                        + "Luego presione el botón \"Ver\".\n"
                        + "Otro posible error: el valor seleccionado no tiene un identificador válido.",2);
            }
            cDF();
        }else{
            GV.mensajeAccessDenied();
        }
    }//GEN-LAST:event_btnRestaurarMouseClicked

    private void btnAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseEntered
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnAbrir.getIcon().toString()))));
    }//GEN-LAST:event_btnAbrirMouseEntered

    private void btnAbrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseExited
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnAbrir.getIcon().toString()))));
    }//GEN-LAST:event_btnAbrirMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnEliminar.getIcon().toString()))));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnEliminar.getIcon().toString()))));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnRestaurarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarMouseEntered
        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnRestaurar.getIcon().toString()))));
    }//GEN-LAST:event_btnRestaurarMouseEntered

    private void btnRestaurarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarMouseExited
        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnRestaurar.getIcon().toString()))));
    }//GEN-LAST:event_btnRestaurarMouseExited

    private void cboMostrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMostrarItemStateChanged
        cWT();
        load();
        cDF();
    }//GEN-LAST:event_cboMostrarItemStateChanged

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        txtBuscar.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(final KeyEvent e) {
//                trs.setRowFilter(RowFilter.regexFilter(txtBuscar.getText(), 1));
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(), 0,1,2,3,4,5,7,8,9,10));
            }
            
        });
        
        
        
        trs = new TableRowSorter(modelo);
        
        tblListar.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnCancelar.getIcon().toString()))));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnCancelar.getIcon().toString()))));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        limpiarTextField();
        loadPanels(1);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void txtInstitucionUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstitucionUKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstitucionUKeyTyped

    private void txtInstitucionUKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstitucionUKeyReleased
        institucioValidate(txtInstitucionU);
    }//GEN-LAST:event_txtInstitucionUKeyReleased

    private void txtInstitucionUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstitucionUKeyPressed
        institucioValidate(txtInstitucionN);
    }//GEN-LAST:event_txtInstitucionUKeyPressed

    private void txtInstitucionUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInstitucionUFocusLost
        institucioValidate(txtInstitucionU);
    }//GEN-LAST:event_txtInstitucionUFocusLost

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnModificar.getIcon().toString()))));// TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseExited

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnModificar.getIcon().toString()))));// TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        if(GV.tipoUserAdmin()){
            cWT();

            if(stConvenio == null){
                OptionPane.showMsg("No se pudo cargar el registro", "Error al cargar convenio, no se puede modificar", 3);
                cDF();
                return;
            }
            if(stConvenio.getEstado() == 2){
                try {
                    abrirConvenio(stConvenio.getId());
                    OptionPane.showMsg("No se puede modificar el registro", "El convenio ya se encuentra generado, no se puede modificar", 2);

                    cDF();
                    return;
                } catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                    Logger.getLogger(VConvenios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String nombre = GV.getFilterString(txtNombreU.getText());
            Date fechaIni = txtFechaIniU.getDate();
            Date fechaFin = txtFechaFinU.getDate();
            Date fechaCobro = txtFechaCobroU.getDate();
            try {
                txtPorcentajeAdicionalU.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(VConvenios.class.getName()).log(Level.SEVERE, null, ex);
                GV.mensajeExcepcion("El porcentaje adicional ingresado es incorrecto\n"+ex.getMessage(),2);
            }
            try {
                txtCuotasU.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(VConvenios.class.getName()).log(Level.SEVERE, null, ex);
                GV.mensajeExcepcion("Las cuotas ingresadas son incorrectas\n"+ex.getMessage(),2);
            }
            int cuotas = (int)txtCuotasU.getValue();
            int montoMax = 0;
            int montoPp = 0;
            int cantClientes = 0;
            int idDescuento  =  0;
            String idInstitucion = (getIdInstitucion(txtInstitucionU.getText()));
            int porcAdicional = (int)txtPorcentajeAdicionalU.getValue();
            stConvenio.setNombre(nombre);
            stConvenio.setCuotas(cuotas);
            stConvenio.setFechaCobro(fechaCobro);
            stConvenio.setEstado(1);
            stConvenio.setFechaFin(fechaFin);
            stConvenio.setFechaInicio(fechaIni);
            stConvenio.setIdDescuento(idDescuento);
            stConvenio.setPorcentajeAdicion(porcAdicional);
            if(!idInstitucion.equals(stConvenio.getIdInstitucion())){
                if(GlobalValuesBD.getFichasByConveny(stConvenio.getId()).size() > 0){
                    if(OptionPane.getConfirmation("¿Estas seguro que deseas modificar este convenio?", 
                            "El convenio ya contiene fichas generadas que supuestamente tienen relación con\n"
                                    + "la empresa que estás modificando, si confirmas esta acción\n"
                                    + "todas las fichas generadas pasarán a pertenecer a un convenio con\n"
                                    + " esta nueva institución. ¿Estas seguro?", 2)){
                        stConvenio.setIdInstitucion(idInstitucion);

                    }
                }else{
                    stConvenio.setIdInstitucion(idInstitucion);
                }
            }
            stConvenio.setMaximoClientes(cantClientes);
            stConvenio.setMontoMaximo(montoMax);
            stConvenio.setMontoPp(montoPp);

            if(!load.updateFromUI(stConvenio)){
                cDF();
                return;
            }
            cargarDatos("0");
            cDF();
        }else{
            GV.mensajeAccessDenied();
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    private void txtNombreUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUKeyTyped
        int largo = 45;
        if(txtNombreU.getText().length() >= largo ){
            evt.consume();
            OptionPane.showMsg("Error de ingreso de datos","El nombre solo debe contener hasta 45 caracteres", 2);
        }
    }//GEN-LAST:event_txtNombreUKeyTyped

    private void btnCrearFichasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFichasMouseClicked
        try{
            cWT();
            int fila = tblListar.getSelectedRow();
            int id = Integer.parseInt(tblListar.getValueAt(fila, 0).toString());
            
            stConvenio = (Convenio)GV.buscarPorIdEnLista(""+id, listConvenios, new Convenio());
            if(stConvenio != null || stConvenio.getEstado() > 0){
                
                GV.setConvenio(stConvenio);
                if(GV.fechaFutura(stConvenio.getFechaInicio())){
                    OptionPane.showMsg("No se puede asignar convenio", 
                            "El convenio aún no se puede utilizar,\n"
                            + "la fecha de inicio es superior a la fecha actual.", 2);
                    cDF();
                    return;
                }
                if(GV.fechaPasada(stConvenio.getFechaFin())){
                    OptionPane.showMsg("No se puede asignar convenio", 
                            "El convenio ya no se puede utilizar,\n"
                            + "la fecha de término ya ha pasado.", 2);
                    cDF();
                    return;
                }
                cDF();
                boton.crearFicha();
            }
            
        }catch(Exception e){
            OptionPane.showMsg("Seleccione un elemento en la tabla","Debe hacer clic sobre un elemento de la tabla,\n"
                    + "Luego presione el botón \"Ver\".",  2);
        }
        cDF();
    }//GEN-LAST:event_btnCrearFichasMouseClicked

    private void btnCrearFichasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFichasMouseEntered
        btnCrearFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnCrearFichas.getIcon().toString()))));
    }//GEN-LAST:event_btnCrearFichasMouseEntered

    private void btnCrearFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFichasMouseExited
        btnCrearFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnCrearFichas.getIcon().toString()))));
    }//GEN-LAST:event_btnCrearFichasMouseExited

    private void txtInstitucionNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstitucionNKeyTyped
        int largo = 100;
        if(txtInstitucionN.getText().length() >= largo){
            evt.consume();
            txtInstitucionN.setText("[0]");
            OptionPane.showMsg("Error de ingreso de datos", "La institución ingresada no existe.", 2);
        }
        institucioValidate(txtInstitucionN);
    }//GEN-LAST:event_txtInstitucionNKeyTyped

    private void txtInstitucionNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstitucionNKeyReleased
        institucioValidate(txtInstitucionN);
    }//GEN-LAST:event_txtInstitucionNKeyReleased

    private void txtInstitucionNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstitucionNKeyPressed
        institucioValidate(txtInstitucionN);
    }//GEN-LAST:event_txtInstitucionNKeyPressed

    private void txtInstitucionNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInstitucionNFocusLost
        institucioValidate(txtInstitucionN);
    }//GEN-LAST:event_txtInstitucionNFocusLost

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnGuardar.getIcon().toString()))));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnGuardar.getIcon().toString()))));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if(GV.tipoUserAdmin()){
            cWT();
            String nombre = GV.getFilterString(txtNombreN.getText());
            Date fechaIni = txtFechaIniN.getDate();
            Date fechaFin = txtFechaTerN.getDate();
            Date fechaCobro = txtFechaCobroN.getDate();
            try {
                txtPorcentajeAdicionalN.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(VConvenios.class.getName()).log(Level.SEVERE, null, ex);
                GV.mensajeExcepcion("El porcentaje adicional ingresado es incorrecto\n"+ex.getMessage(),2);
            }
            try {
                txtCuotasN.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(VConvenios.class.getName()).log(Level.SEVERE, null, ex);
                GV.mensajeExcepcion("Las cuotas ingresadas son incorrectas\n"+ex.getMessage(),2);
            }
            int cuotas = (int)txtCuotasN.getValue();
            int montoMax = 0;
            int montoPp = 0;
            int cantClientes = 0;
            int idDescuento  =  0;
            String idInstitucion = getIdInstitucion(txtInstitucionN.getText());
            int porcAdicional = (int)txtPorcentajeAdicionalN.getValue();
            Convenio convenio= new Convenio(0, nombre, fechaIni, fechaFin, cuotas,fechaCobro, montoMax, montoPp, cantClientes, idDescuento, porcAdicional, idInstitucion, 1, null, 0);
            if(!load.addFromUI(convenio)){
                cDF();
                return;
            }
            cargarDatos("0");
            cDF();
        }else{
            GV.mensajeAccessDenied();
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void txtNombreNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreNKeyTyped
        int largo = 45;
        if(txtNombreN.getText().length() >= largo){
            evt.consume();
            OptionPane.showMsg("Error de ingreso de datos", "El nombre solo debe contener hasta 45 caracteres", 2);
        }
    }//GEN-LAST:event_txtNombreNKeyTyped

    private void btnPagarCuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarCuotasMouseClicked
        if(GV.tipoUserAdmin()){
            cWT();
            if(stConvenio.getEstado() == 2){
                OptionPane.showOptionPanel(new OpanelPagarCuotasConvenio(stConvenio), OptionPane.titlePayAgreementFees());
            }else{
                try {
                    OptionPane.showMsg("No se puede crear registro", "El convenio aún no está activo o se encuentra pagado.", 2);
                    boton.convenios();
                } catch (SQLException ex) {
                    Logger.getLogger(VConvenios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VConvenios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            cDF();
        }else{
            GV.mensajeAccessDenied();
        }
    }//GEN-LAST:event_btnPagarCuotasMouseClicked

    private void btnPagarCuotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarCuotasMouseEntered
        btnPagarCuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnPagarCuotas.getIcon().toString()))));// TODO add your handling code here:
    }//GEN-LAST:event_btnPagarCuotasMouseEntered

    private void btnPagarCuotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarCuotasMouseExited
        btnPagarCuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnPagarCuotas.getIcon().toString()))));
    }//GEN-LAST:event_btnPagarCuotasMouseExited

    private void btnMostrarCuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarCuotasMouseClicked
        cWT();
        GV.printCuotasConvenio(stConvenio);
        cDF();
    }//GEN-LAST:event_btnMostrarCuotasMouseClicked

    private void btnMostrarCuotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarCuotasMouseEntered
        btnMostrarCuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnMostrarCuotas.getIcon().toString()))));
    }//GEN-LAST:event_btnMostrarCuotasMouseEntered

    private void btnMostrarCuotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarCuotasMouseExited
        btnMostrarCuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnMostrarCuotas.getIcon().toString()))));
    }//GEN-LAST:event_btnMostrarCuotasMouseExited

    private void institucioValidate(JTextField txt){
        if(GV.strToNumber(txt.getText()) > 0){
            txt.setForeground(Color.black);
        }else{
            txt.setForeground(Color.red);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbrir;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnCrearFichas;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnMostrarCuotas;
    private javax.swing.JLabel btnPagarCuotas;
    private javax.swing.JLabel btnRestaurar;
    private javax.swing.JComboBox<String> cboMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JTable tblListar;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JSpinner txtCuotasN;
    private javax.swing.JSpinner txtCuotasU;
    private com.toedter.calendar.JDateChooser txtFechaCobroN;
    private com.toedter.calendar.JDateChooser txtFechaCobroU;
    private com.toedter.calendar.JDateChooser txtFechaFinU;
    private com.toedter.calendar.JDateChooser txtFechaIniN;
    private com.toedter.calendar.JDateChooser txtFechaIniU;
    private com.toedter.calendar.JDateChooser txtFechaTerN;
    private javax.swing.JTextField txtInstitucionN;
    private javax.swing.JTextField txtInstitucionU;
    private javax.swing.JTextField txtNombreN;
    private javax.swing.JTextField txtNombreU;
    private javax.swing.JSpinner txtPorcentajeAdicionalN;
    private javax.swing.JSpinner txtPorcentajeAdicionalU;
    // End of variables declaration//GEN-END:variables

    private void load(){
        if(cboMostrar.getSelectedIndex()==0){//en nueva version cargar ventana completa con lista de clientes estatica global
            cargarDatos("0");
        }else{
            cargarDatos("-1");
        }
    }
    private void cargarDatos(String listar) {
        limpiarTextField();
        loadPanels(1);
        listConvenios = load.listar(listar, new Convenio());
        if(listar.equals("-1")){
            btnRestaurar.setVisible(true);
            btnEliminar.setVisible(false);
            btnAbrir.setVisible(false);
            btnModificar.setVisible(false);
        }else{
            btnRestaurar.setVisible(false);
            btnEliminar.setVisible(true);
            btnAbrir.setVisible(true);
            btnModificar.setVisible(true);
        }
        try{
            modelo.setNumRows(0);
            for (Object object : listConvenios) {
                Convenio temp = (Convenio)object;
                GV.convenioUpdateBDIfValidated(temp);
                Institucion ins = (Institucion)load.get(temp.getIdInstitucion(), 0, new Institucion());
                String insName = (ins != null)?((Institucion)ins).getNombre():"No asignada";
                String estado = (temp.getEstado() == 1)?"Activo":"Generado";
                estado=(temp.getEstado()==3)?"Pagado":estado;
                Object[] fila = new Object[5];
                fila[0] = temp.getId();
                fila[1] = temp.getNombre();
                fila[2] = insName;
                fila[3] = (listar.equals("-1"))?"Anulado":estado;
                modelo.addRow(fila);
            }
            tblListar.updateUI();
            if(tblListar.getRowCount() == 0){
                GV.emptyTable(cboMostrar, txtBuscar, "Convenios");
            }
            
        }catch(Exception e){
            OptionPane.showMsg("Ocurrió un error inesperado", "Ocurrió un error inesperado al cargar valores en la tabla, ["+e.getMessage()+"]",3);
        }
    }

    private void abrirConvenio(int id) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        loadPanels(2);
        stConvenio = (Convenio)GV.buscarPorIdEnLista(""+id, listConvenios, new Convenio());
            if(stConvenio!=null){
                if(stConvenio.getEstado() > 1){
                    setBtnVisible(true);
                }else{
                    setBtnVisible(false);
                }
                if(stConvenio.getEstado() == 3){
                    btnPagarCuotas.setVisible(false);
                }
                if(stConvenio.getNombre().isEmpty() || stConvenio.getNombre().equals("null"))
                    txtNombreU.setText("");
                else
                    txtNombreU.setText(stConvenio.getNombre());
                txtFechaIniU.setDate(stConvenio.getFechaInicio());
                txtFechaFinU.setDate(stConvenio.getFechaFin());
                txtFechaCobroU.setDate(stConvenio.getFechaCobro());
                txtPorcentajeAdicionalU.setValue((int)stConvenio.getPorcentajeAdicion());
                txtCuotasU.setValue(stConvenio.getCuotas());
                if(stConvenio.getIdInstitucion().isEmpty())
                    txtInstitucionU.setText("");
                else
                    txtInstitucionU.setText("["+stConvenio.getIdInstitucion()+"] "+((Institucion)load.get(stConvenio.getIdInstitucion(), 0, new Institucion())).getNombre());
                
            }else{
                OptionPane.showMsg("Seleccione registro","Error al cargar valores,\n"
                    + "es posible que no se haya seleccionado un registro\n"
                    + "o el valor seleccionado no tiene un identificador válido.",2);
            }
    }

    private void limpiarTextField() {
        txtNombreU.setText("");
        txtNombreN.setText("");
        txtCuotasN.setValue((int)1);
        txtCuotasU.setValue((int)1);
        txtFechaFinU.setDate(null);
        txtFechaIniN.setDate(null);
        txtFechaCobroN.setDate(null);
        txtFechaIniU.setDate(null);
        txtFechaTerN.setDate(null);
        txtFechaCobroU.setDate(null);
        txtInstitucionN.setText("");
        txtInstitucionU.setText("");
    }

    private void autocompletar() throws SQLException, ClassNotFoundException {
        TextAutoCompleter textAutoCompleter1 = new TextAutoCompleter(txtInstitucionN);
        TextAutoCompleter textAutoCompleter2 = new TextAutoCompleter(txtInstitucionU);
        
        textAutoCompleter1.setMode(0);
        textAutoCompleter2.setMode(0);
        for (Object object : load.listar("0", new Institucion())) {
            Institucion temp = (Institucion)object;
            
            textAutoCompleter1.addItem("["+temp.getCod()+"] "+temp.getNombre());
            textAutoCompleter1.setMode(0);
            
            textAutoCompleter2.addItem("["+temp.getCod()+"] "+temp.getNombre());
            textAutoCompleter2.setMode(0);
        }
    }
    
    private void cWT(){
        GV.cursorWAIT(this);
    }
    private void cDF(){
        GV.cursorDF(this);
    }

    private void loadPanels(int option) {
        if(option ==2){
            pnl1.setVisible(false);
            pnl2.setVisible(true);
        }else{
            pnl1.setVisible(true);
            pnl2.setVisible(false);
        }
    }

    private void setBtnVisible(boolean b) {
        btnMostrarCuotas.setVisible(b);
        btnPagarCuotas.setVisible(b);
    }

    private String getIdInstitucion(String text) {
        if(text!=null){
            text = ((text.startsWith("[")) && (text.contains("]")))?text.substring(1, text.indexOf("]")):null;
            text = (!(GV.getFilterString(text).isEmpty()))?text:null;
        }
        return text;
    }
}
